# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pupils',
            field=models.ManyToManyField(related_name='teachers', to='classes.Pupil'),
        ),
    ]
